<a href="https://colab.research.google.com/github/kirtimistri/Machine_Learning/blob/main/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [13]:
titanic=pd.read_csv("https://github.com/YBI-Foundation/Dataset/raw/main/Titanic.csv")

In [14]:
titanic.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [15]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   object
 3   sex        1309 non-null   object
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   object
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object
 10  embarked   1307 non-null   object
 11  boat       486 non-null    object
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object
dtypes: float64(3), int64(4), object(7)
memory usage: 143.3+ KB

In [16]:
titanic.describe()

,pclass,survived,age,sibsp,parch,fare,body
count,1309.000000,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,121.000000
mean,2.294882,0.381971,29.881138,0.498854,0.385027,33.295479,160.809917
std,0.837836,0.486055,14.413493,1.041658,0.865560,51.758668,97.696922
min,1.000000,0.000000,0.170000,0.000000,0.000000,0.000000,1.000000
25%,2.000000,0.000000,21.000000,0.000000,0.000000,7.895800,72.000000
50%,3.000000,0.000000,28.000000,0.000000,0.000000,14.454200,155.000000
75%,3.000000,1.000000,39.000000,1.000000,0.000000,31.275000,256.000000
max,3.000000,1.000000,80.000000,8.000000,9.000000,512.329200,328.000000

In [17]:
pd.read_html('https://github.com/YBI-Foundation/Dataset/raw/main/Titanic.html')

[          0         1          2                            3       4      5   \
 0     pclass  survived       name                          sex     age  sibsp
 1          1         1      Allen       Miss. Elisabeth Walton  female     29
 2          1         1    Allison        Master. Hudson Trevor    male   0.92
 3          1         0    Allison          Miss. Helen Loraine  female      2
 4          1         0    Allison  Mr. Hudson Joshua Creighton    male     30
 ...      ...       ...        ...                          ...     ...    ...
 1305       3         0     Zabour                 Miss. Hileni  female   14.5
 1306       3         0     Zabour                Miss. Thamine  female    NaN
 1307       3         0   Zakarian              Mr. Mapriededer    male   26.5
 1308       3         0   Zakarian                    Mr. Ortin    male     27
 1309       3         0  Zimmerman                      Mr. Leo    male     29

          6       7       8         9         10    11    12         13
 0     parch  ticket    fare     cabin  embarked  boat  body  home.dest
 1         0       0   24160  211.3375        B5     S     2        NaN
 2         1       2  113781  151.5500   C22 C26     S    11        NaN
 3         1       2  113781  151.5500   C22 C26     S   NaN        NaN
 4         1       2  113781  151.5500   C22 C26     S   NaN        135
 ...     ...     ...     ...       ...       ...   ...   ...        ...
 1305      1       0    2665   14.4542       NaN     C   NaN        328
 1306      1       0    2665   14.4542       NaN     C   NaN        NaN
 1307      0       0    2656    7.2250       NaN     C   NaN        304
 1308      0       0    2670    7.2250       NaN     C   NaN        NaN
 1309      0       0  315082    7.8750       NaN     S   NaN        NaN

 [1310 rows x 14 columns]]

In [18]:
titanic.tail()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.5,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.0,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.0,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

In [19]:
titanic.describe(include="all")

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
count,1309.000000,1309.000000,1309,1309,1046.000000,1309.000000,1309.000000,1309,1308.000000,295,1307,486,121.000000,745
unique,NaN,NaN,1307,2,NaN,NaN,NaN,929,NaN,186,3,27,NaN,369
top,NaN,NaN,"Connolly, Miss. Kate",male,NaN,NaN,NaN,CA. 2343,NaN,C23 C25 C27,S,13,NaN,"New York, NY"
freq,NaN,NaN,2,843,NaN,NaN,NaN,11,NaN,6,914,39,NaN,64
mean,2.294882,0.381971,NaN,NaN,29.881138,0.498854,0.385027,NaN,33.295479,NaN,NaN,NaN,160.809917,NaN
std,0.837836,0.486055,NaN,NaN,14.413493,1.041658,0.865560,NaN,51.758668,NaN,NaN,NaN,97.696922,NaN
min,1.000000,0.000000,NaN,NaN,0.170000,0.000000,0.000000,NaN,0.000000,NaN,NaN,NaN,1.000000,NaN
25%,2.000000,0.000000,NaN,NaN,21.000000,0.000000,0.000000,NaN,7.895800,NaN,NaN,NaN,72.000000,NaN
50%,3.000000,0.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN,NaN,155.000000,NaN
75%,3.000000,1.000000,NaN,NaN,39.000000,1.000000,0.000000,NaN,31.275000,NaN,NaN,NaN,256.000000,NaN
max,3.000000,1.000000,NaN,NaN,80.000000,8.000000,9.000000,NaN,512.329200,NaN,NaN,NaN,328.000000,NaN

In [20]:
titanic.shape

(1309, 14)

In [21]:
titanic.columns

Index(['pclass', 'survived', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket',
       'fare', 'cabin', 'embarked', 'boat', 'body', 'home.dest'],
      dtype='object')

In [22]:
titanic['sex']

0       female
1         male
2       female
3         male
4       female
         ...
1304    female
1305    female
1306      male
1307      male
1308      male
Name: sex, Length: 1309, dtype: object

In [23]:
titanic['sex'].shape

(1309,)

In [24]:
titanic[['sex']]

         sex
0     female
1       male
2     female
3       male
4     female
...      ...
1304  female
1305  female
1306    male
1307    male
1308    male

[1309 rows x 1 columns]

In [25]:
titanic[['sex']].shape

(1309, 1)

In [26]:
titanic['sex'].unique()

array(['female', 'male'], dtype=object)

In [27]:
titanic['sex'].value_counts()

male      843
female    466
Name: sex, dtype: int64

In [28]:
titanic.isna().sum()

pclass          0
survived        0
name            0
sex             0
age           263
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        2
boat          823
body         1188
home.dest     564
dtype: int64

In [29]:
titanic.isnull().sum()

pclass          0
survived        0
name            0
sex             0
age           263
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        2
boat          823
body         1188
home.dest     564
dtype: int64